image: leapp-hero
image_title: Leapp Header
col_left_title: "IAM ZERO-TRUST AT SCALE"
col_left_subtitle: "<p>Reduce IAM-related risks through a developer-centric solution.</p><p> From Developer’s Cloud security posture to company’s identity least privilege</p>"
primary_cta: "Install Leapp"
primary_cta_url: "/download/desktop-app"
secondary_cta:
secondary_cta_url:
