image: leapp-hero
image_title: Leapp Header
col_left_title: "Zero-trust IAM at scale"
col_left_subtitle: "Reduce IAM risks by approaching a developer-centric solution. From Developer’s Cloud security posture to company’s identity least privilege"
primary_cta: "Install Leapp"
primary_cta_url: "#"
secondary_cta: "Watch the Demo"
secondary_cta_url: "#"
