email: your-email@example.com

# SEO in <head>
title: Leapp - One step away from your Cloud
description: >- # this means to ignore newlines until "baseurl:"
  Leapp is the tool to access your cloud; 
  It securely stores your access information and generates temporary credential sets to access AWS and Azure Cloud environments.
  It manage AWS Single Sign-On and access to EC2 instances through SSM

# Facebook & Twitter in <head>
facebook_username: a
twitter_username: a
github_username:  a

# Configuration
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.leapp.cloud' # for github pages leave it like this

# Navbar title
navbar_title: Leapp

# Navbar urls
blog_url: 'e'
github_download_url: 'https://github.com/Noovolari/leapp/releases/latest'
github_roadmap_url: 'https://github.com/Noovolari/leapp/projects/4'
github_url: 'https://github.com/Noovolari/leapp'
facebook_url: 'b'
twitter_url: 'a'
linkedin_url: 'f'

sass:
  sass_dir: assets/css
  style: compressed

# -----------------------------------
# ----- Don't edit below this! ------

# Build settings
plugins:
  - jekyll-feed

# Includes directories not in normal template
include:
  - _pages

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
