email: your-email@example.com

# SEO in <head>
title: Leapp - One step away from your Cloud
description: >- # this means to ignore newlines until "baseurl:"
  Leapp is the tool to access your cloud; 
  It securely stores your access information and generates temporary credential sets to access AWS and Azure Cloud environments.
  It manage AWS Single Sign-On and access to EC2 instances through SSM

# Facebook & Twitter in <head>
facebook_username: #
twitter_username: #
github_username:  #

# Configuration
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.leapp.cloud' # for github pages leave it like this

# Navbar title
navbar_title: Leapp

# Navbar urls
blog_url: '#'
github_download_url: 'https://github.com/Noovolari/leapp/releases/latest'
github_roadmap_url: 'https://portal.productboard.com/vtc7td5yjfptmgdsxnoorwwr/tabs/4-in-progress'
github_url: 'https://github.com/Noovolari/leapp'
get_started: 'https://docs.leapp.cloud/installation/install-leapp/'
facebook_url: '#'
twitter_url: '#'
linkedin_url: '#'
slack: 'https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q'

sass:
  sass_dir: assets/css
  style: compressed

jekyll-uglify:
    harmony: true # Enable experimental ES6 conversion

# -----------------------------------
# ----- Don't edit below this! ------

# Build settings
plugins:
  - jekyll-feed
  - uglifier

# Includes directories not in normal template
include:
  - _pages

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
