email: info@noovolari.com

# SEO in <head>
title: Leapp - Make the switch, today.
description: >- # this means to ignore newlines until "baseurl:"
  Manage your Cloud credentials locally and improve your workflow with the only open-source desktop app you’ll ever need.

# Facebook & Twitter in <head>
facebook_username: #
twitter_username: #
github_username:  #

# Configuration
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.leapp.cloud' # for github pages leave it like this

# Navbar title
navbar_title: Leapp

# Navbar urls
blog_url: 'https://blog.leapp.cloud'
github_download_url: 'https://github.com/Noovolari/leapp/releases/latest'
github_roadmap_url: 'https://roadmap.leapp.cloud/tabs/4-in-progress'
github_url: 'https://github.com/Noovolari/leapp'
get_started: 'https://docs.leapp.cloud/latest/installation/install-leapp/'
latest: 'https://docs.leapp.cloud/latest'
facebook_url: '#'
twitter_url: '#'
linkedin_url: '#'
slack: 'https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q'

sass:
  sass_dir: assets/css
  style: compressed

jekyll-uglify:
    harmony: true # Enable experimental ES6 conversion

# -----------------------------------
# ----- Don't edit below this! ------

# Build settings
plugins:
  - jekyll-feed
  - uglifier

# Includes directories not in normal template
include:
  - _pages

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - values:
      hero_class: "default-hero"
