title: "SET YOUR CLOUD SECURITY STANDARDS"
image: steps/step3.svg
avatar: illustrations/31.svg
color: green
features:
  - icon: fa-vault
    content: "Save your long term credentials safely and generate a set of short-term credentials constantly rotated"
    cta_text: Read the Doc!
    cta_url: "https://docs.leapp.cloud/latest/security/credentials-generation/aws/"
  - icon: fa-handshake
    content: "Every data is stored securely in the System Vault, rely on end-to end encryption to share Leapp access Configurations."
    cta_text: Read the Doc!
    cta_url: "https://docs.leapp.cloud/latest/security/system-vault/"
  - icon: fa-binary-lock
    content: "Comply with the Cloud Providers security standards to access the Cloud."
    cta_text: Login to Leapp Team!
    cta_url: "https://app.leapp.cloud"
