benefits:
  - title: "20 min"
    description: Time of automatic credentials rotation
  - title: "4.5M $"
    description: On average, saved avoiding data breaches, due to credentials compromised or stolen*
  - title: 19%
    description: Of total data breaches attack come from credentials compromise.*
post_scriptum: "* From a <a href='https://www.ibm.com/reports/data-breach' target='_blank'>2023 report by IBM</a>"
