benefits:
  - title: "20 min"
    description: Time of automatic credentials rotation
  - title: 10x
    description: Risk reduction in Cloud credentials breach
  - title: 3 hrs
    description: Saved every week for opening multiple Console and operating in Cloud*
post_scriptum:
